eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: '8001'
spring:
  application:
    name: corevalue-service
